version: "3"
services:
  backend:
    container_name: omm-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2000:2000"
    depends_on:
      - mongo
    networks:
      - be
      - db

  mongo:
    image: mongo
    networks:
      - db
    volumes:
      - ./data:/data/db
networks:
  be:
  db:
